export const MIN_DEPARTMENT_ZOOM = 3;
export const MAX_DEPARTMENT_ZOOM = 7.5;
export const MIN_PROVINCE_ZOOM = MAX_DEPARTMENT_ZOOM;
export const MAX_PROVINCE_ZOOM = 9.5;
export const MIN_DISTRICT_ZOOM = MAX_PROVINCE_ZOOM;
export const INITIAL_ZOOM = 5;
